title: Vote For The Democrat
email: joey@voteforthedemocrat.org
description: It really is that simple.
baseurl: "/"
url: "https://www.voteforthedemocrat.org"
permalink: pretty
image: http://www.voteforthedemocrat.org/assets/images/logo.png

defaults:
  -
    scope:
      path: "president"
    values:
      layout: candidate
      race: president
      delegates: 0
  -
    scope:
      path: "senate"
    values:
      layout: candidate
      race: senate
  -
    scope:
      path: "house"
    values:
      layout: candidate
      race: house

# Build settings
markdown: kramdown

exclude:
  - .DS_Store
  - .gitignore
  - .github
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
